# -*- coding: utf-8 -*-
"""fuzzy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xdt9KvUJw3dY1XKb0HuVvZHpJgLe2a3e

# Readme.md
## Detecção Inteligente de Spam Utilizando Machine Learning e Lógica Fuzzy

## Integrantes
- Maria Clara Guerreira Moita Viana
- Maria Fernanda Lopes Rodrigues de Sousa
- João Gabriel Leite Neirelli
- João Victor Martins Albernaz


## Objetivo

Desenvolver um sistema capaz de identificar mensagens SMS classificando-as como Spam ou Não Spam através de Machine Learning e complementar essa análise utilizando Lógica Fuzzy para determinar o grau de suspeita da mensagem.

## Tecnologias Utilizadas

- Python
- Google Colab
- Pandas
- NumPy
- Scikit-Learn
- Scikit-Fuzzy
- Matplotlib

## Fluxo da Solução

Mensagem SMS

⬇️

Pré-processamento (TF-IDF)

⬇️

Árvore de Decisão

⬇️

Probabilidade de Spam

⬇️

Sistema Fuzzy

⬇️

Grau de Suspeita

## Base de Dados

SMS Spam Collection Dataset

- Total de mensagens: 5572
- Classes:
  - Spam
    - Ham (Não Spam)

    ## Metodologia

    ### Machine Learning
    - Vetorização de texto com TF-IDF
    - Treinamento usando Árvore de Decisão
    - Avaliação por matriz de confusão e métricas de classificação

  ### Sistema Fuzzy
    Entradas:
    - Probabilidade de Spam
    - Quantidade de Links

    Saída:
    - Grau de Suspeita

  ## Resultado Esperado

    O sistema deve identificar mensagens suspeitas e fornecer uma avaliação mais interpretável através da integração entre Machine Learning e Lógica Fuzzy.

Importando os dados

Importando libs
"""

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    ConfusionMatrixDisplay,
    classification_report
)

"""Criando o dataframe

"""

df = pd.read_csv("/content/spam.csv", encoding="latin-1")
df.head()

#remova colunas vazias
df = df[['v1', 'v2']]
df.head()

"""Criando vetores numéricos para o programa"""

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(df["v2"])

"""Resposta correta e conversão"""

y = df["v1"].map({
    "ham": 0,
    "spam": 1
})

"""Treino e teste"""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

"""Árvore"""

modelo = DecisionTreeClassifier(random_state=42)

"""Treinando"""

modelo.fit(X_train, y_train)

"""Previsões"""

y_pred = modelo.predict(X_test)

"""Calculando métricas"""

#acurácia
print("Acurácia:", accuracy_score(y_test, y_pred))

#precisão
print("Precisão:", precision_score(y_test, y_pred))

#recall
print("Recall:", recall_score(y_test, y_pred))

#f1-score
print("F1:", f1_score(y_test, y_pred))

"""Matriz de confusão"""

cm = confusion_matrix(y_test, y_pred)

disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot()

plt.show()

"""---

# Implementando o Fuzzy
"""

!pip install scikit-fuzzy

"""Importando libs"""

import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl

"""Variáveis fuzzy"""

links = ctrl.Antecedent(np.arange(0, 11, 1), 'links')
palavras = ctrl.Antecedent(np.arange(0, 11, 1), 'palavras')
suspeita = ctrl.Consequent(np.arange(0, 101, 1), 'suspeita')

"""Funções de pertinência"""

#links
links['baixo'] = fuzz.trimf(links.universe, [0, 0, 4])
links['medio'] = fuzz.trimf(links.universe, [2, 5, 8])
links['alto'] = fuzz.trimf(links.universe, [6, 10, 10])

#palavras suspeitas
palavras['baixo'] = fuzz.trimf(palavras.universe, [0, 0, 4])
palavras['medio'] = fuzz.trimf(palavras.universe, [2, 5, 8])
palavras['alto'] = fuzz.trimf(palavras.universe, [6, 10, 10])

#grau de suspeita
suspeita['baixa'] = fuzz.trimf(suspeita.universe, [0, 0, 40])
suspeita['media'] = fuzz.trimf(suspeita.universe, [20, 50, 80])
suspeita['alta'] = fuzz.trimf(suspeita.universe, [60, 100, 100])

#gráficos
links.view()
palavras.view()
suspeita.view()

"""Regras"""

regra1 = ctrl.Rule(links['alto'] & palavras['alto'], suspeita['alta'])

regra2 = ctrl.Rule(links['alto'] & palavras['medio'], suspeita['alta'])

regra3 = ctrl.Rule(links['medio'] & palavras['alto'], suspeita['alta'])

regra4 = ctrl.Rule(links['medio'] & palavras['medio'], suspeita['media'])

regra5 = ctrl.Rule(links['baixo'] & palavras['medio'], suspeita['media'])

regra6 = ctrl.Rule(links['baixo'] & palavras['baixo'], suspeita['baixa'])

"""Sistema"""

sistema = ctrl.ControlSystem([
    regra1,
    regra2,
    regra3,
    regra4,
    regra5,
    regra6
])

simulador = ctrl.ControlSystemSimulation(sistema)

"""Teste:
mensagem com 8 links e 9 palavras suspeitas
"""

simulador.input['links'] = 8
simulador.input['palavras'] = 9

simulador.compute()

print(simulador.output['suspeita'])

#resultado
suspeita.view(sim=simulador)
